[package]
name = "cch23-avdhoot"
version = "0.1.0"
edition = "2021"

[dependencies]
cch23-validator = "15.0.1"
rocket = { version = "0.5.0", features = ["json"] }
shuttle-rocket = "0.35.1"
shuttle-runtime = "0.35.1"
tokio = "1.26.0"
